version: "3"

services:

    db-service:
        container_name: db-service
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db
        ports:
            - 5433:5432
        volumes:
            - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
            - /var/www/wcp/db:/var/lib/postgresql/data
        networks: 
            - wcp-network

networks: 
    wcp-network:
        driver: bridge
